WW.Components = {
  maps: null,
  selectedMapIndex: null,
  init: function(){
    this.maps = [new this.Map(WW.Data.Layouts.big, [
      new WW.Components.Team('blue', [
        new WW.Data.Units.Infantry(4, 1, 'blue'),
        new WW.Data.Units.Mech(6, 8, 'blue'),
        new WW.Data.Units.APC(6, 9, 'blue'),
        new WW.Data.Units.Recon(12, 9, 'blue'),
        new WW.Data.Units.Tank(7, 5, 'blue'),
        new WW.Data.Units.MediumTank(2, 3, 'blue'),
        new WW.Data.Units.NeoTank(2, 21, 'blue'),
        new WW.Data.Units.AntiAir(8, 27, 'blue'),
        new WW.Data.Units.Artillery(9, 24, 'blue'),
        new WW.Data.Units.Rockets(18, 22, 'blue'),
        new WW.Data.Units.Missiles(37, 22, 'blue'),
        new WW.Data.Units.Fighter(30, 12, 'blue'),
        new WW.Data.Units.Bomber(21, 11, 'blue'),
        new WW.Data.Units.BCopter(18, 6, 'blue'),
        new WW.Data.Units.TCopter(12, 1, 'blue'),
        new WW.Data.Units.Battleship(18, 9, 'blue'),
        new WW.Data.Units.Cruiser(20, 15, 'blue'),
        new WW.Data.Units.Lander(28, 14, 'blue'),
        new WW.Data.Units.Submarine(28, 18, 'blue'),
      ]),
      new WW.Components.Team('red', [
        new WW.Data.Units.Infantry(54, 17, 'red'),
        new WW.Data.Units.Mech(50, 12, 'red'),
        new WW.Data.Units.APC(41, 6, 'red'),
        new WW.Data.Units.Recon(34, 4, 'red'),
        new WW.Data.Units.Tank(28, 7, 'red'),
        new WW.Data.Units.MediumTank(19, 1, 'red'),
        new WW.Data.Units.NeoTank(14, 3, 'red'),
        new WW.Data.Units.AntiAir(8, 1, 'red'),
        new WW.Data.Units.Artillery(2, 7, 'red'),
        new WW.Data.Units.Rockets(3, 12, 'red'),
        new WW.Data.Units.Missiles(6, 15, 'red'),
        new WW.Data.Units.Fighter(11, 13, 'red'),
        new WW.Data.Units.Bomber(10, 5, 'red'),
        new WW.Data.Units.BCopter(3, 4, 'red'),
        new WW.Data.Units.TCopter(2, 19, 'red'),
        new WW.Data.Units.Battleship(23, 18, 'red'),
        new WW.Data.Units.Cruiser(29, 16, 'red'),
        new WW.Data.Units.Lander(29, 14, 'red'),
        new WW.Data.Units.Submarine(25, 11, 'red'),
      ]),
      new WW.Components.Team('green', [
        new WW.Data.Units.Infantry(7, 16, 'green'),
        new WW.Data.Units.Mech(8, 22, 'green'),
        new WW.Data.Units.APC(7, 28, 'green'),
        new WW.Data.Units.Recon(12, 28, 'green'),
        new WW.Data.Units.Tank(19, 27, 'green'),
        new WW.Data.Units.MediumTank(25, 31, 'green'),
        new WW.Data.Units.NeoTank(28, 22, 'green'),
        new WW.Data.Units.AntiAir(32, 27, 'green'),
        new WW.Data.Units.Artillery(38, 31, 'green'),
        new WW.Data.Units.Rockets(45, 29, 'green'),
        new WW.Data.Units.Missiles(49, 27, 'green'),
        new WW.Data.Units.Fighter(2, 6, 'green'),
        new WW.Data.Units.Bomber(2, 4, 'green'),
        new WW.Data.Units.BCopter(7, 6, 'green'),
        new WW.Data.Units.TCopter(15, 5, 'green'),
        new WW.Data.Units.Battleship(20, 16, 'green'),
        new WW.Data.Units.Cruiser(27, 16, 'green'),
        new WW.Data.Units.Lander(27, 20, 'green'),
        new WW.Data.Units.Submarine(24, 18, 'green'),
      ]),
      new WW.Components.Team('yellow', [
        new WW.Data.Units.Infantry(33, 12, 'yellow'),
        new WW.Data.Units.Mech(41, 15, 'yellow'),
        new WW.Data.Units.APC(47, 9, 'yellow'),
        new WW.Data.Units.Recon(2, 12, 'yellow'),
        new WW.Data.Units.Tank(10, 22, 'yellow'),
        new WW.Data.Units.MediumTank(13, 12, 'yellow'),
        new WW.Data.Units.NeoTank(15, 9, 'yellow'),
        new WW.Data.Units.AntiAir(16, 13, 'yellow'),
        new WW.Data.Units.Artillery(13, 18, 'yellow'),
        new WW.Data.Units.Rockets(10, 18, 'yellow'),
        new WW.Data.Units.Missiles(1, 19, 'yellow'),
        new WW.Data.Units.Fighter(16, 1, 'yellow'),
        new WW.Data.Units.Bomber(17, 9, 'yellow'),
        new WW.Data.Units.BCopter(14, 13, 'yellow'),
        new WW.Data.Units.TCopter(23, 0, 'yellow'),
        new WW.Data.Units.Battleship(29, 8, 'yellow'),
        new WW.Data.Units.Cruiser(28, 13, 'yellow'),
        new WW.Data.Units.Lander(24, 18, 'yellow'),
        new WW.Data.Units.Submarine(21, 21, 'yellow'),
      ]),
      new WW.Components.Team('black', [
        new WW.Data.Units.Infantry(5, 2, 'black'),
        new WW.Data.Units.Mech(4, 7, 'black'),
        new WW.Data.Units.APC(43, 26, 'black'),
        new WW.Data.Units.Recon(41, 19, 'black'),
        new WW.Data.Units.Tank(35, 19, 'black'),
        new WW.Data.Units.MediumTank(46, 9, 'black'),
        new WW.Data.Units.NeoTank(3, 7, 'black'),
        new WW.Data.Units.AntiAir(2, 1, 'black'),
        new WW.Data.Units.Artillery(0, 10, 'black'),
        new WW.Data.Units.Rockets(0, 27, 'black'),
        new WW.Data.Units.Missiles(4, 19, 'black'),
        new WW.Data.Units.Fighter(19, 13, 'black'),
        new WW.Data.Units.Bomber(21, 20, 'black'),
        new WW.Data.Units.BCopter(14, 13, 'black'),
        new WW.Data.Units.TCopter(28, 19, 'black'),
        new WW.Data.Units.Battleship(24, 14, 'black'),
        new WW.Data.Units.Cruiser(27, 10, 'black'),
        new WW.Data.Units.Lander(25, 20, 'black'),
        new WW.Data.Units.Submarine(19, 21, 'black'),
      ]),
    ])];
    this.selectedMapIndex = 0;
  },
  update: function(){
    this.maps.forEach(map => map.update());
  },
  draw: function(){
    this.Background.draw();
    this.maps[this.selectedMapIndex].draw();
  },
  getCurrentMap: function(){
    return this.maps[this.selectedMapIndex];
  }
};